[package]
name = "governor"
version = "0.1.0"
authors = ["Andreas Fuchs <asf@boinkor.net>"]
edition = "2018"

[dev-dependencies]
crossbeam = "0.6.0"
libc = "0.2.41"

[features]
default = ["std"]
std = ["parking_lot", "evmap", "nonzero_ext/std"]
no_std = []

[dependencies]
nonzero_ext = {version = "0.1.5", default-features = false}
parking_lot = {version = "0.9.0", optional = true}
evmap = {version = "6.0.0", optional = true}
