[package]
name = "ratelimit_meter_rewrite"
version = "0.1.0"
authors = ["Andreas Fuchs <asf@boinkor.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
crossbeam = "0.6.0"

[features]
default = ["std"]
std = ["parking_lot", "evmap", "nonzero_ext/std"]

[dependencies]
nonzero_ext = {version = "0.1.5", default-features = false}
parking_lot = {version = "0.9.0", optional = true}
evmap = {version = "6.0.0", optional = true}
derive_more = "0.99.1"