[advisories]
version = 2

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "MIT",
    "Unicode-DFS-2016",
]
confidence-threshold = 0.8

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
highlight = "lowest-version"
allow = [
    #{ name = "ansi_term", version = "=0.11.0" },
]
deny = [
]
# Certain crates/versions that will be skipped when doing duplicate detection.
skip = [
    #{ name = "ansi_term", version = "=0.11.0" },
]
skip-tree = [
    # criterion & proptest pull in old versions of rand & are dev-dependencies:
    { name = "criterion", version = "*", depth = 3 },
    { name = "proptest", version = "*", depth = 3 },
]
