name: "CI"
on:
  workflow_call:

jobs:
  cargo_bench:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: rust_tests
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: dtolnay/rust-toolchain@stable
      - run: "cargo bench"
