name: "Additional CI"
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  cargo_deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "cargo deny"
      uses: EmbarkStudios/cargo-deny-action@v1
      with:
        command: "check all"
  cargo_clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "cargo clippy"
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: -- -D warnings
