name: "Code coverage"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  code_coverage:
    uses: boinkor-net/ci-baseline-rust/.github/workflows/ci_baseline_rust_coverage.yml@coverage
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
